### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by bvreede** [hetutrechtsarchief/Utrecht-In-Perspectief#52]
Wat een geweldige tool hebben jullie gemaakt! @marcovanegmond1969 heeft er zojuist over verteld in onze wekelijkse meeting bij de UB.
Ik vroeg me af of jullie al hebben overwogen om een licentie te geven aan de software, zodat deze ook door anderen gebruikt kan worden, onder voor jullie belangrijke voorwaarden?

**Comment by companje** [comment]
Hey Barbara! Ja zeker, de code is open source en we willen graag dat ook anderen er mooie dingen mee gaan maken en de code ook weer delen. De code is beschikbaar onder GNU GPLv3 licentie.

**Comment by bvreede** [comment]
Ah top! Waar staat de licentie? Ik kan 'm niet vinden...
