### ISSUE TITLE
Verversen pagina geeft 'Not found'

### ISSUE THREAD

**Issue by marcovanegmond1969** [hetutrechtsarchief/Utrecht-In-Perspectief#54]
Bij 'Reload this page' in browser (in elk geval Chrome) krijg je de melding 

Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at utrechtinperspectief.nl Port 80

En met 'Back' kom je dan in eerste instantie niet terug op de vorige pagina

**Comment by emacgillavry** [comment]
Duplicate of https://github.com/hetutrechtsarchief/Utrecht-In-Perspectief/issues/45
