### ISSUE TITLE
Schakelen tussen 1669 en 1684 na kiezen gebouw gaat bij profielen niet helemaal goed

### ISSUE THREAD

**Issue by marcovanegmond1969** [hetutrechtsarchief/Utrecht-In-Perspectief#55]
Na het kiezen van een gebouw en vervolgens switchen tussen 1669 en 1684 geeft niet het juiste, ingezoomde beeld bij de profielen.

**Comment by emacgillavry** [comment]
Zie https://github.com/hetutrechtsarchief/Utrecht-In-Perspectief/issues/28
